import streamlit as st
import plotly.graph_objects as go

# --------------------------------------------------
# PAGE CONFIGURATION
# --------------------------------------------------

st.set_page_config(
    page_title="RouteWise",
    page_icon="🚚",
    layout="wide"
)

# --------------------------------------------------
# TITLE
# --------------------------------------------------

st.title("🚚 RouteWise")

st.subheader(
    "Last-Mile Delivery Route Optimizer & Late-Delivery Risk Predictor"
)

st.write(
    "A smart dashboard for optimizing delivery routes "
    "and identifying late-delivery risks."
)

# --------------------------------------------------
# KPI SECTION
# --------------------------------------------------

st.divider()

st.header("📌 Delivery Overview")

# Dummy values for dashboard development
total_orders = 30
total_vehicles = 4
optimized_distance = 36.2
high_risk_deliveries = 2

col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric("Total Orders", total_orders)

with col2:
    st.metric("Vehicles", total_vehicles)

with col3:
    st.metric(
        "Optimized Distance",
        f"{optimized_distance:.1f} km"
    )

with col4:
    st.metric(
        "High-Risk Deliveries",
        high_risk_deliveries
    )

# --------------------------------------------------
# BASELINE VS OPTIMIZED
# --------------------------------------------------

st.divider()

st.header("📊 Baseline vs Optimized")

baseline_distance = 50.0
optimized_distance = 36.2

distance_saved = baseline_distance - optimized_distance

improvement = (
    distance_saved / baseline_distance
) * 100

col1, col2, col3 = st.columns(3)

with col1:
    st.metric(
        "Baseline Distance",
        f"{baseline_distance:.1f} km"
    )

with col2:
    st.metric(
        "Optimized Distance",
        f"{optimized_distance:.1f} km"
    )

with col3:
    st.metric(
        "Distance Improvement",
        f"{improvement:.1f}%"
    )

# --------------------------------------------------
# ROUTE VISUALIZATION
# --------------------------------------------------

st.divider()

st.header("🗺️ Delivery Route")

# Dummy route coordinates
locations = {
    "Depot": (0, 0),
    "Order 1": (2, 3),
    "Order 2": (5, 2),
    "Order 3": (7, 5),
    "Order 4": (4, 7),
}

route = [
    "Depot",
    "Order 1",
    "Order 2",
    "Order 3",
    "Order 4",
    "Depot"
]

x_values = []
y_values = []
labels = []

for location in route:
    x, y = locations[location]

    x_values.append(x)
    y_values.append(y)
    labels.append(location)

fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=x_values,
        y=y_values,
        mode="lines+markers+text",
        text=labels,
        textposition="top center",
        name="Vehicle Route",
        line=dict(width=3),
        marker=dict(size=10)
    )
)

fig.update_layout(
    title="Sample Vehicle Route",
    xaxis_title="Distance X",
    yaxis_title="Distance Y",
    height=500,
    showlegend=True
)

st.plotly_chart(
    fig,
    use_container_width=True
)

# --------------------------------------------------
# CURRENT STATUS
# --------------------------------------------------

st.divider()

st.header("🚦 Current Status")

st.success(
    "Sample route visualization is working successfully."
)

st.info(
    "The sample route will later be replaced with "
    "the actual optimized route generated by OR-Tools."
)